package io.github.kevvvvyp.simpletransactionaloutboxstarter.domain.model;

import java.time.Instant;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@ToString
@Getter
@Setter
@Entity
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "outbox",
		indexes = { @Index(name = "outbox_pkey", columnList = "id", unique = true),
					@Index(name = "deduplication_key_unique_index",
							columnList = "deduplication_key",
							unique = true),
					@Index(name = "outbox_scheduled_at_updated_at_index",
							columnList = "body, locked_by") })
public class OutboxEntity {

	@Id
	@GeneratedValue(generator = "UUID")
	@GenericGenerator(
			name = "UUID",
			strategy = "org.hibernate.id.UUIDGenerator"
	)
	@Type(type="uuid-char")
	@Column(name = "id", columnDefinition = "VARCHAR(36)", nullable = false, unique = true)
	private UUID id;

	@Size(max = 120)
	@Column(name = "sender", nullable = false)
	private String sender;

	@Size(max = 120)
	@Column(name = "recipient", nullable = false)
	private String recipient;

	@Size(max = 120)
	@Column(name = "subject", nullable = false)
	private String subject;

	@Size(max = 120)
	@Column(name = "type", nullable = false)
	private String type;

	@Column(name = "body", nullable = false)
	private String body;

	@GeneratedValue(generator = "UUID")
	@GenericGenerator(
			name = "UUID",
			strategy = "org.hibernate.id.UUIDGenerator"
	)
	@Type(type="uuid-char")
	@Column(name = "locked_by", columnDefinition = "VARCHAR(36)")
	private UUID lockedBy;

	@Size(max = 120)
	@NotNull
	@Column(name = "deduplication_key")
	private String deduplicationKey;

	@NotNull
	@Column(name = "scheduled_after", nullable = false)
	private Instant scheduledAfter;

	//Generated by DB
	@Column(name = "created_at", insertable = false, updatable = false)
	private Instant createdAt;

	@NotNull
	@Column(name = "updated_at", nullable = false)
	private Instant updatedAt;

}