package io.github.kevvvvyp.simpletransactionaloutboxstarter.domain.model;

import java.time.Instant;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Entity for Outbox Table
 */
@ToString
@Getter
@Setter
@Entity
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "outbox",
		indexes = { @Index(name = "outbox_pkey", columnList = "id", unique = true),
					@Index(name = "deduplication_key_unique_index",
							columnList = "deduplication_key",
							unique = true),
					@Index(name = "outbox_scheduled_at_updated_at_index",
							columnList = "body, locked_by") })
public class OutboxEntity {

	/**
	 * Unique Identifier
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.UUID)
	@Column(name = "id", nullable = false, unique = true)
	private UUID id;

	/**
	 * Metadata (Nullable)
	 */
	@Size(max = 120)
	@Column(name = "sender", nullable = false)
	private String sender;

	/**
	 * Metadata (Nullable)
	 */
	@Size(max = 120)
	@Column(name = "recipient", nullable = false)
	private String recipient;

	/**
	 * Metadata (Nullable)
	 */
	@Size(max = 120)
	@Column(name = "subject", nullable = false)
	private String subject;

	/**
	 * Maps to a delivery strategy (Mandatory)
	 */
	@Size(max = 120)
	@Column(name = "type", nullable = false)
	private String type;

	/**
	 * Bodu (Nullable)
	 */
	@Column(name = "body", nullable = false)
	private String body;

	/**
	 * ID of thread that has claimed messages within the outbox.
	 */
	@Column(name = "locked_by")
	private UUID lockedBy;

	/**
	 * Key to dedup messages on
	 */
	@Size(max = 120)
	@NotNull
	@Column(name = "deduplication_key")
	private String deduplicationKey;

	/**
	 * Date to schedule messages on/after.
	 */
	@NotNull
	@Column(name = "scheduled_after", nullable = false)
	private Instant scheduledAfter;

	/**
	 * Metadata
	 */
	//Generated by DB
	@Column(name = "created_at", insertable = false, updatable = false)
	private Instant createdAt;

	/**
	 * Metadata
	 */
	@NotNull
	@Column(name = "updated_at", nullable = false)
	private Instant updatedAt;

}