name: Run Gradle on tag/release

env:
  OSSRH_USERNAME: ${{  secrets. OSSRH_USERNAME }}
  OSSRH_PASSWORD: ${{  secrets. OSSRH_PASSWORD }}
  SIGNING_KEY: ${{  secrets. PUBLISH_SIGNING_KEY }}
  SIGNING_PASSWORD: ${{  secrets. PUBLISH_SIGNING_PASSWORD }}

on:
  push:
    tags:
      - "*"

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Configure release version
        run: echo "RELEASE_VERSION=${GITHUB_BASE_REF}" >> $GITHUB_ENV

      - name: Log release version
        run: echo "${RELEASE_VERSION}"

      - name: Remove default github maven configuration
        # This step is a workaround to avoid a decryption issue of Beam's
        # net.linguica.gradle.maven.settings plugin and github's provided maven
        # settings.xml file
        run: rm ~/.m2/settings.xml

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build -x Test

      - name: Run Tests
        run: ./gradlew Test

      - name: Gradle Publish
        run: ./gradlew publish -PreleaseVersion=${RELEASE_VERSION} -PossrhUsername=$OSSRH_USERNAME -PossrhPassword=$OSSRH_PASSWORD -PsigningKey=$SIGNING_KEY -PsigningPassword=$SIGNING_PASSWORD
